import './globals.css'

import type { Metadata } from 'next'
import { Karla } from 'next/font/google'

import { Toaster } from '@/components/ui/toaster'
import { cn } from '@/lib/utils'

const karla = Karla({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={karla.variable}>
      <body
        className={cn(`min-h-screen bg-green-300 px-4 font-sans antialiased`)}
      >
        {children}
        <Toaster />
      </body>
    </html>
  )
}
